name: logguard
description: Securely sanitize logs in Flutter apps by masking passwords, tokens, PII, and other sensitive data with minimal performance overhead.A Flutter plugin for secure log sanitization
version: 0.1.1
homepage: https://github.com/cas8398/logguard
repository: https://github.com/cas8398/logguard
issue_tracker: https://github.com/cas8398/logguard/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.flagodna.logguard
        pluginClass: LogGuardPlugin
